### ISSUE TITLE
-webkit-appearance: none;

### ISSUE THREAD

**Issue by renehesse** [vladocar/Basic.css#11]
on an ios device the buttons and input fields are not displayed nicely. this is probably due to the missing -webkit-appearance: none;

![IMG_96E13824C7CF-1](https://user-images.githubusercontent.com/13309968/83855554-89badd00-a718-11ea-8b84-ec4476a1ddac.jpeg)

**Comment by vladocar** [comment]
Yes, -webkit-appearance: none; was the problem. I fix it. Could you run some tests? It works on my MacBook iOS simulator. Thanks!

**Comment by renehesse** [comment]
it works now, but the distance of the buttons does not fit 
![IMG_8E784546B616-1](https://user-images.githubusercontent.com/13309968/83870082-e674c280-a72d-11ea-9422-fecfe5ba578f.jpeg)

**Comment by vladocar** [comment]
Ok. I added top end bottom margin.

**Comment by renehesse** [comment]
perfect. thanks a lot!
