### ISSUE TITLE
Button Input Types are not treated as buttons

### ISSUE THREAD

**Issue by jon49** [vladocar/Basic.css#4]
Buttons like `<input type=submit value="Click Me">` and `<value type=reset value=Cancel>` are not treated the same as a button `<button>Click Me</button>`.

It would be nice to add them to the `button` tag style:

`button, input[type=submit], input[type=reset] {...`

**Comment by jon49** [comment]
Perhaps even color the reset button differently. But I don't know what the standard color-blind colors are for that. So, I don't have any real suggestion for what color it aught to be.

**Comment by vladocar** [comment]
Thanks for the suggestion. It is fixed. https://vladocar.github.io/Basic.css/

About the reset button color is little tricky. I'm not sure what is the right color or if should be defined in the basic.css or in your additional styles.
