### ISSUE TITLE
Tables are broken in Firefox

### ISSUE THREAD

**Issue by Y-Less** [vladocar/Basic.css#5]
Chrome:

![table-chrome](https://user-images.githubusercontent.com/991078/83634978-59016900-a59b-11ea-88e4-b486babd2e7d.png)

Waterfox 2020.03.1:

![table-waterfox](https://user-images.githubusercontent.com/991078/83635012-69194880-a59b-11ea-90c5-c217a6658479.png)

Firefox mobile:

![table-ffmobile](https://user-images.githubusercontent.com/991078/83635034-6fa7c000-a59b-11ea-9491-11097c3eb74a.png)

They both seem to loose more lines the further down you go.

**Comment by bellwood** [comment]
Seems to be an issue with how Firefox and Chrome handle `border-collapse: collapse`

**Comment by vladocar** [comment]
Actually it was HTML problem. The tbody tag was not closed properly. Fixed.
