### ISSUE TITLE
No color for a:visited

### ISSUE THREAD

**Issue by lucas-deangelis** [vladocar/Basic.css#6]
Nice framework! It seems that there's no color for a:visited. I can make a simple pull request to add what seems to be the default value (#551a8b), however I don't have a good sense for colors so feel free to change it.

**Comment by vladocar** [comment]
Hi Lucas,
Thanks for the suggestion.
I feel that the a:visited is little obsolete and should be optional not default. That is why I will leave the users to decide as a option later in their code.
